#Kibana deployments 


apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:6.5.4
        resources:
          requests:
            cpu: 200m
          limits:
            cpu: 1
        ports:
        - containerPort: 5601
          name: kibana
        livenessProbe:
          httpGet:
            path: /
            port: 5601
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 5601
          initialDelaySeconds: 60
          periodSeconds: 30
        



---

apiVersion: v1
kind: Service
metadata:
  labels:
    name: kibana-ext
  name: kibana-ext
spec:
  selector:
    app: kibana
  type: NodePort
  ports:
  - name: kibana
    protocol: TCP
    port: 5601
